define Creators_Question = [
    {
        "question": "ТА ХЭН БЭ?",
        "voice": "audio/hutlugch12.ogg",
        "choices": ["Сурагч", "Ажилтан", "Уран бүтээлч", "Тоглогч", "Судлаач", "Фэн", "Зүгээр л иргэн"],
        "duration": 25,
        "mode": "survey",
    },
    {
        "question": "ANIMO WORLD ЯМАР ТӨРЛИЙН ЕРТӨНЦ БАЙХ ВЭ?",
        "voice": "audio/hutlugch13.ogg",
        "choices": ["Ирээдүйн", "Уран зөгнөлт", "Орчин үе", "Сүйрлийн дараах"],
        "duration": 25,
        "mode": "survey",
    },
    {
        "question": "ЕРТӨНЦ ХААНА БАЙДАГ ВЭ?",
        "voice": "audio/hutlugch14.ogg",
        "choices": ["ДЭЛХИЙ", "ӨӨР ГАРАГ ЕРТӨНЦ", "ХӨВӨГЧ ЕРТӨНЦ", "ГАЗАР ДООР ЕРТӨНЦ", "ӨӨР ХЭМЖЭЭСТ ЕРТӨНЦ"],
        "duration": 25,
        "mode": "survey",
    },
    {
        "question": "ANIMO ЕРТӨНЦӨД ХЭН АМЬДАРДАГ ВЭ?",
        "voice": "audio/hutlugch15.ogg",
        "choices": ["Хүн", "Робот", "Шидийн амьтан", "Харь гарагийн хүн", "Аниме дүр", "Эльф", "Орк"],
        "duration": 25,
        "mode": "survey",
    },
    {
        "question": "АНИМО ЕРТӨНЦИЙН ОРШИН СУУГЧИД ЯМАР ЗАН, ХАРАКТЕРТЭЙ ВЭ?",
        "voice": "audio/hutlugch16.ogg",
        "choices": ["Тайван дөлгөөн", "Өрсөлдөөнч", "Бүтээлч", "Адал явдалч"],
        "duration": 25,
        "mode": "survey",
    },
    {
        "question": "ТЭДНИЙ ДАЙСАН ХЭН БЭ?",
        "voice": "audio/hutlugch17.ogg",
        "choices": ["The Void — “Хоосрол”", "THE DEVOURER — “Ертөнц залгигч”", "THE COLOSSUS — “Аварга машин”"],
        "duration": 25,
        "mode": "survey",
    },
]

define CROWD_BATTLE_QUESTIONS = [
    {
        "question": "Naruto-д Gaara ямар тосгоны Kazekage вэ?",
        "voice": None,
        "choices": ["Konoha", "Sunagakure", "Kirigakure", "Kumogakure"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "One Piece-д Sanji аль далайд төрсөн бэ?",
        "voice": None,
        "choices": ["East Blue", "West Blue", "North Blue", "South Blue"],
        "correct_index": 2, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Attack on Titan-д Colossal Titan-ийн анхны эзэмшигч хэн байсан бэ?",
        "voice": None,
        "choices": ["Reiner Braun", "Bertholdt Hoover", "Zeke Yeager", "Porco Galliard"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Demon Slayer-д Inosuke ямар амьтны маск зүүдэг вэ?",
        "voice": None,
        "choices": ["Чоно", "Гахай", "Үнэг", "Баавгай"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Jujutsu Kaisen-д Megumi Fushiguro ямар овгийн удамтай вэ?",
        "voice": None,
        "choices": ["Gojo", "Kamo", "Zenin", "Inumaki"],
        "correct_index": 2, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Hunter × Hunter-д Kurapika ямар овгийн сүүлчийн амьд үлдсэн хүмүүсийн нэг вэ?",
        "voice": None,
        "choices": ["Zoldyck", "Kurta", "Freecss", "Nostrade"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Bleach-д Soul Society-ийн 6-р Division-ийн ахлагч хэн бэ?",
        "voice": None,
        "choices": ["Byakuya Kuchiki", "Toshiro Hitsugaya", "Kenpachi Zaraki", "Shunsui Kyoraku"],
        "correct_index": 0, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "My Hero Academia-д Shoto Todoroki-ийн аавын баатрын нэр юу вэ?",
        "voice": None,
        "choices": ["Hawks", "Endeavor", "Best Jeanist", "Eraser Head"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Tokyo Ghoul-д Anteiku ямар газар вэ?",
        "voice": None,
        "choices": ["Сургууль", "Кофе шоп", "Эмнэлэг", "CCG-ийн салбар"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Dragon Ball Z-д Vegeta ямар цолтой дүр вэ?",
        "voice": None,
        "choices": ["Saiyan King", "Prince of Saiyans", "God of Destruction", "Supreme Kai"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Fullmetal Alchemist: Brotherhood-д Roy Mustang ямар төрлийн алхимич вэ?",
        "voice": None,
        "choices": ["Ice Alchemist", "Flame Alchemist", "Steel Alchemist", "Blood Alchemist"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Chainsaw Man-д Power ямар төрлийн Fiend вэ?",
        "voice": None,
        "choices": ["Blood Fiend", "Gun Fiend", "Fox Fiend", "Curse Fiend"],
        "correct_index": 0, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "One Punch Man-д Saitama Hero Association-д анх элсэхдээ ямар rank авдаг вэ?",
        "voice": None,
        "choices": ["C-Class Rank 1", "C-Class Rank 388", "B-Class Rank 101", "A-Class Rank 39"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Sword Art Online-д Asuna ямар guild-ийн дэд удирдагч байсан бэ?",
        "voice": None,
        "choices": ["Laughing Coffin", "Knights of the Blood", "Moonlit Black Cats", "Fuurinkazan"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "JoJo's Bizarre Adventure-д DIO-ийн Stand аль вэ?",
        "voice": None,
        "choices": ["Star Platinum", "The World", "Killer Queen", "King Crimson"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Steins;Gate-д “D-Mail” гэж юу вэ?",
        "voice": None,
        "choices": ["Ирээдүй рүү илгээдэг мессеж", "Өнгөрсөн рүү илгээдэг мессеж", "Нууц байгууллагын код", "Лабораторийн сервер"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Black Clover-д Asta ямар онцгой чадвартай сэлэм ашигладаг вэ?",
        "voice": None,
        "choices": ["Fire Magic", "Anti-Magic", "Time Magic", "Dark Magic"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "One Punch Man-д Genos ямар төрлийн дүр вэ?",
        "voice": None,
        "choices": ["Alien", "Cyborg", "Esper", "Monster"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Mob Psycho 100-д Mob-ийн жинхэнэ нэр хэн бэ?",
        "voice": None,
        "choices": ["Shigeo Kageyama", "Ritsu Kageyama", "Arataka Reigen", "Teruki Hanazawa"],
        "correct_index": 0, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Haikyuu!!-д Hinata ямар ахлах сургуульд тоглодог вэ?",
        "voice": None,
        "choices": ["Nekoma", "Aoba Johsai", "Karasuno", "Shiratorizawa"],
        "correct_index": 2, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Blue Lock-д Isagi Yoichi ямар байрлалд ихэвчлэн тоглодог вэ?",
        "voice": None,
        "choices": ["Goalkeeper", "Defender", "Striker", "Wing-back"],
        "correct_index": 2, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Spy × Family-д Anya ямар онцгой чадвартай вэ?",
        "voice": None,
        "choices": ["Ирээдүй хардаг", "Бодол уншдаг", "Үл үзэгддэг", "Цаг зогсоодог"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Vinland Saga-д Thorfinn-ийн аавын нэр хэн бэ?",
        "voice": None,
        "choices": ["Askeladd", "Thors", "Canute", "Leif"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Fairy Tail-д Natsu ямар төрлийн Dragon Slayer вэ?",
        "voice": None,
        "choices": ["Lightning", "Fire", "Iron", "Sky"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Black Clover-д Yuno ямар төрлийн magic-аар хамгийн алдартай вэ?",
        "voice": None,
        "choices": ["Wind Magic", "Fire Magic", "Water Magic", "Dark Magic"],
        "correct_index": 0, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Death Note-д Shinigami Eyes-тэй болохын тулд хүн юу золиослох ёстой вэ?",
        "voice": None,
        "choices": ["Өөрийн дурсамжийн тал хувийг", "Үлдсэн амьдралынхаа тал хувийг", "Death Note-оо эзэмших эрхээ", "Өөрийн нэрээ"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Demon Slayer-д Rengoku ямар Hashira вэ?",
        "voice": None,
        "choices": ["Sound Hashira", "Flame Hashira", "Mist Hashira", "Stone Hashira"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Jujutsu Kaisen-д Toge Inumaki яагаад ихэнхдээ хоолны орцны нэрээр ярьдаг вэ?",
        "voice": None,
        "choices": ["Хэл ярианы асуудалтай", "Cursed Speech-ээ санамсаргүй ашиглахаас сэргийлдэг", "Нууц код ашигладаг", "Зүгээр л дадал"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Naruto-д Minato Namikaze ямар хочоор алдартай вэ?",
        "voice": None,
        "choices": ["Copy Ninja", "Yellow Flash", "White Fang", "Demon of the Mist"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
    {
        "question": "Pokémon anime-д Ash Ketchum анх гараагаа эхлэхдээ аль Pokémon-ыг авахыг хүсэж байсан ч хоцорсон бэ?",
        "voice": None,
        "choices": ["Bulbasaur", "Squirtle", "Charmander", "Pikachu"],
        "correct_index": 1, "duration": 25, "attack_power": 100, "enemy_attack_power": 100,
    },
]
