define Creators_Question = [
    {
        "question": "ТА ХЭН БЭ?",
        "voice": "audio/hutlugch12.ogg",
        "choices": ["Student", "Worker", "Creators", "Gamer", "Explorer", "Fan", "Just Here"],
        "duration": 15,
        "mode": "survey",
    },
    {
        "question": "ANIMO World ямар төрлийн ертөнц байх вэ?",
        "voice": "audio/hutlugch13.ogg",
        "choices": ["Futuristic", "Fantasy", "Modern", "Post-apocalyptic"],
        "duration": 15,
        "mode": "survey",
    },
    {
        "question": "Ертөнц хаана байдаг вэ?",
        "voice": "audio/hutlugch14.ogg",
        "choices": ["Earth", "Another Planet", "Floating World", "Underground", "Another Dimension"],
        "duration": 15,
        "mode": "survey",
    },
    {
        "question": "ANIMO Ертөнцөд ХЭН амьдардаг ВЭ?",
        "voice": "audio/hutlugch15.ogg",
        "choices": ["Humans", "Robots", "Magic Creatures", "Aliens", "Anime Characters", "Elfs", "Monsters", "Orcs"],
        "duration": 15,
        "mode": "survey",
    },
    {
        "question": "Анимо Ертөнцийн оршин суугчид ямар зан, характертай вэ?",
        "voice": "audio/hutlugch16.ogg",
        "choices": ["Peaceful", "Competitive", "Creative", "Adventurous", "Adventurous"],
        "duration": 15,
        "mode": "survey",
    },
]

define CROWD_BATTLE_QUESTIONS = [
    {
        "question": "Naruto-д Kakashi-ийн Sharingan-г хэн өгсөн бэ?",
        "voice": "audio/asuult1.ogg",
        "choices": ["Itachi", "Obito", "Madara", "Shisui"],
        "correct_index": 1, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "One Piece-д Luffy-ийн анхны bounty хэд байсан бэ?",
        "voice": "audio/asuult2.ogg",
        "choices": ["10 сая Berry", "20 сая Berry", "30 сая Berry", "50 сая Berry"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Death Note-д Light Yagami анх Death Note-г хаана олдог вэ?",
        "voice": "audio/asuult3.ogg",
        "choices": ["Сургууль дээр", "Гудамжинд", "Сургуулийн дээвэр дээр", "Сургуулийн талбайн ойролцоо"],
        "correct_index": 3, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Attack on Titan-д Levi ямар бүлгийн ахлагч вэ?",
        "voice": "audio/asuult4.ogg",
        "choices": ["Garrison Regiment", "Military Police", "Survey Corps-ийн Special Operations Squad", "Training Corps"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Demon Slayer-д Tanjiro-ийн ээмэг ямар загвартай вэ?",
        "voice": "audio/asuult5.ogg",
        "choices": ["Нарны зурагтай Hanafuda ээмэг", "Сарны зурагтай", "Галын зурагтай", "Лууны зурагтай"],
        "correct_index": 0, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Dragon Ball-д Super Saiyan хэлбэрт анх хэн хүрсэн бэ?",
        "voice": "audio/asuult6.ogg",
        "choices": ["Vegeta", "Gohan", "Goku", "Bardock"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Spirited Away-д Chihiro-ийн эцэг эх юу болж хувирдаг вэ?",
        "voice": "audio/asuult7.ogg",
        "choices": ["Гахай", "Чоно", "Сүнс", "Мангас"],
        "correct_index": 0, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Studio Ghibli-ийн \"My Neighbor Totoro\"-д Totoro-г хүүхдүүд ямар амьтантай төстэй гэж харж болох вэ?",
        "voice": "audio/asuult8.ogg",
        "choices": ["Муур", "Баавгай", "Том ой модны сүнс / амьтан маягийн сүнс", "Үнэг"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Toy Story-ийн эхний кинонд Buzz Lightyear өөрийгөө юу гэж боддог вэ?",
        "voice": "audio/asuult9.ogg",
        "choices": ["Тоглоом", "Жинхэнэ сансрын хамгаалагч", "Робот", "Сансрын судлаач хүн"],
        "correct_index": 1, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "The Lion King-д Simba-г өсөж том болоход нь хэн хамгийн их тусалдаг вэ?",
        "voice": "audio/asuult10.ogg",
        "choices": ["Rafiki", "Zazu", "Timon & Pumbaa", "Scar"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "WALL-E дэлхий дээр ямар үндсэн ажил хийдэг робот вэ?",
        "voice": "audio/asuult11.ogg",
        "choices": ["Хүнийг хамгаалах", "Хог шахаж цэвэрлэх", "Ургамал тарих", "Машин засах"],
        "correct_index": 1, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "How to Train Your Dragon-д Toothless ямар төрлийн луу вэ?",
        "voice": "audio/asuult12.ogg",
        "choices": ["Deadly Nadder", "Gronckle", "Night Fury", "Monstrous Nightmare"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "\"Your Name\" (Kimi no Na wa)-ийн гол хоёр дүрийн нэр хэн бэ?",
        "voice": "audio/asuult13.ogg",
        "choices": ["Taki & Mitsuha", "Haku & Chihiro", "Haru & Yuki", "Ren & Aoi"],
        "correct_index": 0, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Jujutsu Kaisen-д Gojo Satoru-ийн нүдний гол чадвар юу вэ?",
        "voice": "audio/asuult14.ogg",
        "choices": ["Byakugan", "Sharingan", "Six Eyes", "Rinnegan"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Fullmetal Alchemist-д ах дүү Elric нарын гол зорилго юу вэ?",
        "voice": "audio/asuult15.ogg",
        "choices": ["Philosopher's Stone олох", "Ээжийгээ сэргээх", "Бие махбодоо буцааж авах", "Homunculus-уудыг устгах"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "Hunter x Hunter-д Gon-ийн хамгийн алдартай найз хэн бэ?",
        "voice": "audio/asuult16.ogg",
        "choices": ["Hisoka", "Killua", "Kurapika", "Leorio"],
        "correct_index": 1, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "\"Arcane\" animation аль тоглоомын ертөнцөд үндэслэсэн бэ?",
        "voice": "audio/asuult17.ogg",
        "choices": ["Dota 2", "Overwatch", "League of Legends", "Valorant"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "\"Jujutsu Kaisen\"-д Sukuna-ийн хуруу нийт хэд байдаг вэ?",
        "voice": "audio/asuult18.ogg",
        "choices": ["10", "15", "20", "25"],
        "correct_index": 2, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "\"One Punch Man\"-д Saitama өдөр бүр хэдэн удаа суниалт болон суулт хийдэг вэ?",
        "voice": "audio/asuult19.ogg",
        "choices": ["50", "100", "200", "500"],
        "correct_index": 1, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
    {
        "question": "\"Howl's Moving Castle\"-ийн гол дүр Howl ямар мэргэжилтэй вэ?",
        "voice": "audio/asuult20.ogg",
        "choices": ["Шулам", "Шидтэн", "Алхимич", "Анчин"],
        "correct_index": 1, "duration": 15, "attack_power": 25, "enemy_attack_power": 20,
    },
]
