services:
  - type: web
    name: animo-crowd-battle
    runtime: python
    rootDir: voting_server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 8 --timeout 120 app:app
    healthCheckPath: /api/health
    autoDeploy: true
